# Generated by Django 3.0.2 on 2020-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Father_Name', models.CharField(max_length=30)),
                ('DOB', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Marital_Status', models.CharField(max_length=10)),
                ('Email_Id', models.CharField(max_length=50)),
                ('Mob_No', models.IntegerField()),
                ('Address', models.TextField(max_length=500)),
                ('City', models.CharField(max_length=20)),
                ('Pin_Code', models.IntegerField()),
                ('State', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
    ]
